# Generated by Django 5.0 on 2024-10-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_add_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_book',
            name='address',
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='city',
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='state',
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='zipcode',
        ),
    ]
