# Generated by Django 5.0 on 2024-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_add_book_address_remove_add_book_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_book',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='add_book',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='add_book',
            name='email',
            field=models.CharField(default='Unknown', max_length=80),
        ),
        migrations.AddField(
            model_name='add_book',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='add_book',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='add_book',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='add_book',
            name='zipcode',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_book',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
