# Generated by Django 5.0 on 2024-10-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_book_address_add_book_city_add_book_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_book',
            old_name='first_name',
            new_name='book_name',
        ),
    ]
